alias: COMI_Quicksort

generate-output: false
interactive: true

params:
  title: Quicksort
  source: Curso OMI

  visibility: 1

  languages: all

  time_limit: 1000
  memory_limit: 32768
  output_limit: 16384
  stack_limit: 10485760

  overall_wall_time_limit: 60000

  validator: literal
  validator_time_limit: 3000
  extra_wall_time: 0

  email_clarifications: 0
