language: python

python:
- '3.5'

install:
- pip install pipenv
- pushd omegaUp-deploy
- pipenv install

script:
- pipenv run python3 deploy.py --onlychanges "../Busquedas/Adivina el Numero"
- pipenv run python3 deploy.py --onlychanges "../Busquedas/De Cuarto en Cuarto"
- pipenv run python3 deploy.py --onlychanges "../Busquedas/Derrame de Petroleo"
- pipenv run python3 deploy.py --onlychanges "../Busquedas/Pacman"
- pipenv run python3 deploy.py --onlychanges "../Estructuras de Datos Avanzadas/Las Pistas de Azul"
- pipenv run python3 deploy.py --onlychanges "../Estructuras de Datos Avanzadas/Mesa Redonda"
- pipenv run python3 deploy.py --onlychanges "../Estructuras de Datos Avanzadas/Paseo por el Bosque"
- pipenv run python3 deploy.py --onlychanges "../Estructuras de Datos Avanzadas/Round Robin"
- pipenv run python3 deploy.py --onlychanges "../Estructuras de Datos/Cola Interactivo"
- pipenv run python3 deploy.py --onlychanges "../Estructuras de Datos/Conectate"
- pipenv run python3 deploy.py --onlychanges "../Estructuras de Datos/Parentesis"
- pipenv run python3 deploy.py --onlychanges "../Estructuras de Datos/Pila Interactivo"
- pipenv run python3 deploy.py --onlychanges "../Estructuras de Datos/Taquitos"
- pipenv run python3 deploy.py --onlychanges "../Funciones/Funciones Matematicas"
- pipenv run python3 deploy.py --onlychanges "../Funciones/Recuerdame"
- pipenv run python3 deploy.py --onlychanges "../Funciones/Recursion"
- pipenv run python3 deploy.py --onlychanges "../Matematicas/Binomios"
- pipenv run python3 deploy.py --onlychanges "../Matematicas/Criba"
- pipenv run python3 deploy.py --onlychanges "../Matematicas/Entre Conjuntos"
- pipenv run python3 deploy.py --onlychanges "../Matematicas/Jugando con Congruencias"
- pipenv run python3 deploy.py --onlychanges "../Matematicas/Permutacion"
- pipenv run python3 deploy.py --onlychanges "../Matematicas/Simplificar Fracciones"
- pipenv run python3 deploy.py --onlychanges "../Matematicas/Troyo el Cometriangulos"
- pipenv run python3 deploy.py --onlychanges "../Matematicas/Variacion con Repeticion"
- pipenv run python3 deploy.py --onlychanges "../Ordenamiento y Complejidad/Bubble"
- pipenv run python3 deploy.py --onlychanges "../Ordenamiento y Complejidad/Bucket"
- pipenv run python3 deploy.py --onlychanges "../Ordenamiento y Complejidad/Insertion"
- pipenv run python3 deploy.py --onlychanges "../Ordenamiento y Complejidad/Merge"
- pipenv run python3 deploy.py --onlychanges "../Ordenamiento y Complejidad/Quicksort"
- pipenv run python3 deploy.py --onlychanges "../Programacion Basica/A+B"
- pipenv run python3 deploy.py --onlychanges "../Programacion Basica/Canchas"
- pipenv run python3 deploy.py --onlychanges "../Programacion Basica/ContandoInfinito"
- pipenv run python3 deploy.py --onlychanges "../Programacion Basica/Excursion"
- pipenv run python3 deploy.py --onlychanges "../Programacion Basica/Fraccion Mixta"
- pipenv run python3 deploy.py --onlychanges "../Programacion Basica/Palindromos"
- pipenv run python3 deploy.py --onlychanges "../Programacion Basica/Revancha"
- pipenv run python3 deploy.py --onlychanges "../Programacion Basica/Sentados o Parados"
- pipenv run python3 deploy.py --onlychanges "../Programacion Basica/Sequia"
- pipenv run python3 deploy.py --onlychanges "../Programacion Basica/Tak-Tak Tree"
- pipenv run python3 deploy.py --onlychanges "../Programacion Basica/Traductor"
- pipenv run python3 deploy.py --onlychanges "../Programacion Basica/Triples"

env:
  global:
  - secure: r4dk13NNX6OcnDtXDCAd5gbEVYJUubfPWtWWK+ZbMAckICJ2CKmfw3XTnBUj6F9BWpeLt9FSpQGkF54vqnRfR4XSrQUS47BhHy37ej03y0O6AMh5WGdFqhQA52w/4b+rxfhLrn/V0QY4HHhT+pifXcXdFN2TMir6lfF1mkyvdS90fy1QCT4oXHh2JE4dh1hNOXIGUXlkdvHiaJVoViGBNOoMH4GwYV/mkBdCZcAAhW8JE15Er89Kc5fYZ3aCtOY0QdzrX1BWE5fwuQe6DyrNpa2lbw5psBmSgH45o84JK8xIZRQnAzdIAo00L4mAP4YuR4Y5a5H+N37+fYBtv6wlJe8paD6aMU9sMr6TM1qWh9EwRfOhNhgj9WFQl/dU5mQrjhlrJeINfKNPbAeKYvhHyRxaC3g3o7zdlXY/qckUA40GubpN/TAoNPPFiO0KgskpYV0k5JDSJ1i7mwotGJys3FVPDoO92mE9M6Qc19BsWBTzz/ZPlHVDeKrC/nkCrL8cMSSWC1Lj5tE2hZBoqnZyvfKXZbJhRttgcz46VL2+AFNxgGBXZQIavlYQnisayNsgEGl4BZYu57XvcO/dSmeBkOXo38m/oZ68lkxp9ZPHvoT3NbA+25vJVT0wB/kGbRFzJAQceIF4TFaiD9eKpDrg8SLUPEgYy5xdAEbyiUBqQUI=
  - secure: TlMAuEK4ZrSn34bbYmeM2yFfzceAlzFfgp38KbgJiKekE9Sg8honnIkApSIPHPeXaNQN5jkDfLmS+MxesBB6Xpeo5KV3mXJV7OPI7F8je3Lf7z7dD3UU38LQiNJ3rEaiF9hFhznEfrK5L2CposHQ+ZnEGmA6M7xFtjcKvr6h5ZRQpaqNa3qGF9CXKp2G8KcPUSh7xGCCrDQ+Cj/BXIMrnKH6mTgWsuKgjRCC3L8XdBDrBTQuroTQMi5hBmug0b5VFVn/bK2+NaaEV7xt2HGIWC/Z8RQKr2TdfYgewOpABg+PPTn0+uB5Jt1Yu3rKRr/l6LLu4PulnGmvurkvmk/jJ15+aQMlEiBBDN9NknCiiqtX7JC+p2cx0P+pZE70ZjJAFs017enSIb23BLCVor4jzlbbJZihOuAjV+ht1H/b3sulC8P5YDk/7pmibkji6iEZyGKKe4i0k2NRP9yV1/4pbo8KJEreR45V7AG0Vwr82ZhSxorLQmFgpk9usZRnbpxigx4b3e1g/g9BmWHrOzWHtTv0bQDxsqqkbhkTzxFne8e2xPnt3NORGpQ58wJyCHwdX3JRGdcWGQL43OlLeyMkaBQDEbZUZqXrpUtLQ+YDt+96WAbE4Qa2qNRCMR+9ncTU9CBEHMlQ97e7QbULhdwnCO1FzRk1FLED8ZYuuH4ftPo=
